name: flutter_metrics_sdk
description: >
  A lightweight Flutter performance analytics SDK to capture real-user
  metrics such as render time, frame drops, user interactions, and crashes.
version: 1.2.0
homepage: https://github.com/favadthottathil/flutter_metrics_sdk
repository: https://github.com/favadthottathil/flutter_metrics_sdk
issue_tracker: https://github.com/favadthottathil/flutter_metrics_sdk/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
