name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.44.3'
          channel: 'stable'

      - uses: action/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-  
              

      
      - run: flutter pub get

      - run: dart format --set-exit-if-changed .

      - run: flutter analyze --fatal-warnings --fatal-infos

      - run: flutter test --coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info
          fail_ci_if_error: true